/**:
  ros__parameters:
    pose_names: ["up", "down", "left", "right", "fore", "aft"] # We need to declare them here so we can search them by name
    up:
        poses: [0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
        times: [5.0]
        reference: "relative"
    down:
        poses: [0.0, 0.0, -0.2, 0.0, 0.0, 0.0]
        times: [5.0]
        reference: "relative"
    left:
        poses: [0.0, 0.2, 0.0, 0.0, 0.0, 0.0]
        times: [5.0]
        reference: "relative"
    right:
        poses: [0.0, -0.2, 0.0, 0.0, 0.0, 0.0]
        times: [5.0]
        reference: "relative"
    fore:
        poses: [0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
        times: [5.0]
        reference: "relative"
    aft:
        poses: [-0.2, 0.0, 0.0, 0.0, 0.0, 0.0]
        times: [5.0]
        reference: "relative"
