/**:
  ros__parameters:
    number_of_joints: 7                                                # We need this to split up the position arrays
    joint_config_names: ["home", "ready"]                              # We need to declare them here so we can search them by name
    home:
        positions: [1.63, 0.0, 2.88, 1.59, 0.0, -1.57, 0.0]
        times: [10.0]
    ready:
        positions: [2.02, -0.335, 0.949, 1.47, -0.267, -1.42, 0.0]
        times: [10.0]
